[toolchain]
anchor_version = "0.31.1"
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
nft_marketplace = "A3SWqF5HhaZzvQ1VNyncN9u4AerDwatEUVTVVSE9Hrp4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
testsvm = "bash scripts/setup.sh && cargo test"
