[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
assignment_0 = "2GotrbKN8YT7fPhgbisRsdR9BzfLgL7GAFrr14skUDBQ"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
