[package]
name = "assignment-2"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
mpl-token-metadata = "5.1.1"
solana-client = "2.1.21"
solana-commitment-config = "2.1.21"
solana-sdk = "2.1.21"
solana-system-interface = "1.0.0"          # no features needed
spl-associated-token-account-interface = "1.0.0"
spl-token-interface = "1.0.0"
tokio = { version = "1.52.2", features = ["full"] }
