[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
nft_staking = "J3YnvbaxuLdTRrdf4eUoAPnS9zPAnwAsxcHCun5iPSun"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
