[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
instruction_introspection = "8qoU6VhEPekaod9EmVxU8BKND6SPfxhvWF2gaWhHAqgH"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
